apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: owovk3xlf-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: owovk3xlf-nodejs 
  name: owovk3xlf-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: owovk3xlf-nodejs 
